### GET sykmeldt overview
GET http://localhost:8080/api/v1/sykmeldt/oppfolgingsplaner/oversikt
Authorization: Bearer {{token}}

> {%
    client.global.set("oppflgingsplanUuid", response.body.oppfolgingsplaner[0].uuid);
%}

### GET oppfolginsplan
GET http://localhost:8080/api/v1/sykmeldt/oppfolgingsplaner/{{oppflgingsplanUuid}}
Authorization: Bearer {{token}}


### GET oppfolginsplan pdf
GET http://localhost:8080/api/v1/sykmeldt/oppfolgingsplaner/2a821f0c-9e20-4fe8-855b-fa42ad8706d9/pdf
Authorization: Bearer {{token}
