### Create/update oppfolgingsplan utkast
PUT http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner/utkast HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "evalueringsdato": "2025-07-30",
  "content": {
    "formIdentifier": "syfo-oppfolgingsplan",
    "formSemanticVersion": "1.0.0",
    "formSnapshotVersion": "2.0.0",
    "sections": [
      {
        "sectionId": "arbeidsdag",
        "sectionTitle": "Arbeidsdag"
      }
    ],
    "fieldSnapshots": [
        {
            "fieldId": "arbeidsdag_1",
            "fieldType": "TEXT",
            "label": "Beskriv en vanlig arbeidsdag",
            "value": "Her beskrives en vanlig arbeidsdag for den sykmeldte.",
            "sectionId": "arbeidsdag"
        }
    ]
  }
}

### Get oppfolgingsplan utkast
GET http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner/utkast HTTP/1.1
Authorization: Bearer {{token}}

### Create oppfolgingsplan
POST http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "evalueringsdato": "2025-09-30",
  "skalDelesMedLege": false,
  "skalDelesMedVeileder": false,
  "content": {
    "formIdentifier": "syfo-oppfolgingsplan",
    "formSemanticVersion": "1.0.0",
    "formSnapshotVersion": "2.0.0",
    "sections": [
      {
        "sectionId": "arbeidsoppgaver",
        "sectionTitle": "Arbeidsoppgaver"
      },
      {
        "sectionId": "oppfolging",
        "sectionTitle": "Oppfølging og medvirkning"
      }
    ],
    "fieldSnapshots": [
      {
        "fieldId": "arbeidsoppgaver_1",
        "fieldType": "TEXT",
        "label": "Hvordan ser en vanlig arbeidsdag ut?",
        "description": "Beskriv en vanlig arbeidsdag og hvilke oppgaver arbeidstaker gjør på jobben.",
        "value": "Jeg beskriver en vanlig arbeidsdag for den sykmeldte.",
        "sectionId": "arbeidsoppgaver"
      },
      {
        "fieldId": "harAnsattDeltatt",
        "fieldType": "RADIO_GROUP",
        "label": "Har den ansatte deltatt i utarbeidelsen av planen?",
        "description": "Hvis du svarer nei blir du bedt om en begrunnelse.",
        "sectionId": "oppfolging",
        "options": [
          {
            "optionId": "deltattJa",
            "optionLabel": "Ja",
            "wasSelected": "true"
          },
          {
            "optionId": "deltattNei",
            "optionLabel": "Nei",
            "wasSelected": "false"
          }
        ]
      }
    ]
  }
}

### GET Oversikt
GET http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner/oversikt HTTP/1.1
Authorization: Bearer {{token}}

> {%
    client.global.set("oppflgingsplanUuid", response.body.oppfolgingsplan.uuid);
%}

### Del med veileder
POST http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner/{{oppflgingsplanUuid}}/del-med-veileder HTTP/1.1
Authorization: Bearer {{token}}

### Del med Lege
POST http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner/{{oppflgingsplanUuid}}/del-med-lege HTTP/1.1
Authorization: Bearer {{token}}

### GET Oppfolgingsplan by uuid
GET http://localhost:8080/api/v1/arbeidsgiver/{{narmestelederId}}/oppfolgingsplaner/{{oppflgingsplanUuid}} HTTP/1.1
Authorization: Bearer {{token}}
