### POST Påminnelse
POST http://localhost:8080/api/v1/narmesteleder/{{narmestelederId}}/oppfolgingsplaner/paaminnelse HTTP/1.1
Authorization: Bearer {{token}}

### GET Påminnelse
GET http://localhost:8080/api/v1/narmesteleder/{{narmestelederId}}/oppfolgingsplaner/paaminnelse HTTP/1.1
Authorization: Bearer {{token}}

### DELETE Påminnelse
DELETE http://localhost:8080/api/v1/narmesteleder/{{narmestelederId}}/oppfolgingsplaner/paaminnelse HTTP/1.1
Authorization: Bearer {{token}}

### GET Påminnelse
GET http://localhost:8080/api/v1/narmesteleder/{{narmestelederId}}/oppfolgingsplaner/paaminnelse HTTP/1.1
Authorization: Bearer {{token}}
