apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-oppfolgingsplan-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 300m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: syfo-oppfolgingsplan-backend-instance
            envVarPrefix: OPPFOLGINGSPLAN_DB
        diskAutoresize: true
  ingresses:
    - "https://syfo-oppfolgingsplan-backend.intern.nav.no"
  tokenx:
    enabled: true
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: syfo-oppfolgingsplan-frontend
        - application: syfomodiaperson
          namespace: teamsykefravr
    outbound:
      rules:
        - application: arkivporten
        - application: syfooppdfgen
        - application: dinesykmeldte-backend
        - application: isdialogmelding
          namespace: teamsykefravr
        - application: istilgangskontroll
          namespace: teamsykefravr
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
  kafka:
    pool: nav-prod
  valkey:
    - instance: syfo-oppfolgingsplan-backend
      access: readwrite
  env:
    - name: KTOR_ENV
      value: production
    - name: DINE_SYKMELDTE_BASE_URL
      value: http://dinesykmeldte-backend
    - name: PDFGEN_BASE_URL
      value: http://syfooppdfgen
    - name: ISDIALOGMELDING_BASE_URL
      value: http://isdialogmelding.teamsykefravr
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: DOKARKIV_SCOPE
      value: prod-fss.teamdokumenthandtering.dokarkiv
    - name: ARKIVPORTEN_URL
      value: http://arkivporten
    - name: ARKIVPORTEN_SCOPE
      value: dev-gcp.team-esyfo.arkivporten
    - name: PDL_BASE_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: prod-fss.pdl.pdl-api
